version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: tabletap
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 20000921Lkl
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tabletap_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  web:
    image: tabletap_web:latest
    environment:
      SECRET_KEY: django-insecure-g9hl-mt0w=s5%ve&9dh*dt0fi^#s2g6!^@#%#=4t(b(*^rffvf
      DEBUG: "False"
      ALLOWED_HOSTS: "34.151.143.16,localhost,127.0.0.1"
      DB_NAME: tabletap
      DB_USER: postgres
      DB_PASSWORD: 20000921Lkl
      DB_HOST: postgres
      DB_PORT: "5432"
    networks:
      - tabletap_network
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    networks:
      - tabletap_network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

volumes:
  postgres_data:

networks:
  tabletap_network:
    driver: overlay

configs:
  nginx_config:
    file: ./nginx.conf